ListViewPage + homework
coolerUA/fitness_app pull request #5
Opened 2023-10-08 10:17 UTC by coolerUA

ListViewPage replacement for ExcerciseListView and TrainingListView

2023-10-08 15:43 UTC, VadymPinchuk requested changes
Немає gif файлу який показує роботу додатку ) це має бути завжди у кожному пул реквесті

2023-10-08 15:43 UTC, VadymPinchuk commented on lib/presentation/widgets/list_page.dart
> +class TrainingViewWidget extends StatelessWidget {
якщо вони в одному файлі значить вони або приватні або ж винесіть в окремий файл. те ж саме для наступного

2023-10-08 15:43 UTC, VadymPinchuk commented on lib/presentation/widgets/list_page.dart
> +    return widget.viewIndex == 'Exercise'
не бачу сенсу в такій магії.  по суті у них нічого спільного. тому це два окремих пейджа.

2023-10-08 15:43 UTC, VadymPinchuk commented on lib/presentation/widgets/list_page.dart
> +                      PopupMenuItem<SampleItem>(
SampleItem? назва не дуже очевидна

2023-10-08 15:43 UTC, VadymPinchuk commented on lib/presentation/widgets/pages/exercise/new_exercise.dart
> +      widget.user.exercises = [newExercise];
це кошмар. але з цим розберемось пізніше. треба буде переписати стейти )

2023-10-08 15:43 UTC, VadymPinchuk commented on lib/presentation/widgets/pages/exercise/new_exercise.dart
> +                              child: GridView.builder(
велика вкладеність - незручно читати. краще виносити в окремі приватні методи які повертають Widget і вставляти їх в необхідні місця

2023-10-08 15:43 UTC, VadymPinchuk commented on lib/presentation/widgets/pages/workout/new_workout.dart
> +      widget.user.trainings = [newTraining];
також кошмар )

2023-10-09 12:36 UTC, coolerUA commented on lib/presentation/widgets/list_page.dart
> +class TrainingViewWidget extends StatelessWidget {
Make sense. Робив об'єднання в один файл для реюз коду, але так, більш сенсу розбити.

2023-10-09 12:37 UTC, coolerUA commented on lib/presentation/widgets/list_page.dart
> +                      PopupMenuItem<SampleItem>(
Адаптував з інету як тестовий код, так і лишився, забув змінити. Fixed.

2023-10-09 12:39 UTC, coolerUA commented on lib/presentation/widgets/pages/exercise/new_exercise.dart
> +      widget.user.exercises = [newExercise];
Не розумію в чому кошмар, якщо ліста ще немає, то ми додаємо новий елемент. Для пустого ліста не можна ж виконати widget.user.exercises.add(). Принаймі в мене IDE кидає еррор, а в такому випадку синтаксис проходить. 
Щодо стейт-менеджменту я зрозумів вашу позицію, поки не дійде лекція нема що сподіватись)

2023-10-09 12:40 UTC, coolerUA commented on lib/presentation/widgets/pages/exercise/new_exercise.dart
> +                              child: GridView.builder(
Виніс деякі шматки в окремі віджети

2023-10-09 14:08 UTC, VadymPinchuk commented on lib/presentation/widgets/pages/exercise/new_exercise.dart
> +      widget.user.exercises = [newExercise];
Так це кошмар в стейт менеджменті ) головне не запамʼятовувати такий підхід як зараз )

2023-10-09 14:11 UTC, VadymPinchuk approved these changes

2023-10-09 14:11 UTC, VadymPinchuk commented on lib/presentation/widgets/pages/exercise/new_exercise.dart
> -  const NewExcercisePage({super.key, required this.user});
ось так краще лишити )

2023-10-09 14:11 UTC, merged